# Generated by Django 4.0.2 on 2022-03-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_rename_company_lead_company_alter_lead_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=80)),
                ('stage', models.CharField(choices=[('qualification', 'qualification'), ('needs analysis', 'needs analysis'), ('proposal', 'proposal'), ('negotiation', 'negotiation'), ('closed won', 'closed won'), ('closed lost', 'closed lost')], max_length=80)),
                ('close_date', models.DateField(auto_now_add=True)),
                ('opportunity_owner', models.CharField(max_length=80)),
            ],
        ),
    ]
